Checkpoint the RON/WA version of the client side stuff. This had suffered some bitrot, but its now in sync and running on wa44, which is destined to be the source of the next image.

diff --git a/tmcd/ron/emulabctl b/tmcd/ron/emulabctl
--- a/tmcd/ron/emulabctl
+++ b/tmcd/ron/emulabctl
@@ -1,37 +1,181 @@
-#!/bin/sh
+#!/usr/bin/perl -w
 #
 # EMULAB-COPYRIGHT
-# Copyright (c) 2000-2002 University of Utah and the Flux Group.
+# Copyright (c) 2000-2003 University of Utah and the Flux Group.
 # All rights reserved.
 #
-. /etc/emulab/paths.sh
+use Getopt::Std;
+use English;
+use Errno;
+use POSIX qw(strftime);
 
 #
-# Boottime initialization. 
+# Start/Stop the emulab support. Since we do not want to hold up the boot
+# on a remote node, this goes into the background, and exits when done.
+# The stop event kills one on progress. 
 #
-case "$1" in
-start)
-	$BINDIR/watchdog > /dev/null 2>&1 && echo -n ' Emulab'
+sub usage()
+{
+    print "Usage: emulabctl [-n] <start | stop>\n";
+    exit(1);
+}
+my $optlist = "nd";
 
-	#
-	# Do not start the mini server on RON nodes yet. 
-	#
-	if [ -x $BINDIR/webserver.pl -a -e /etc/emulab.pkey ]
-	then
-		$BINDIR/webserver.pl && echo -n ' Webserver'
-	fi
-	;;
-stop)
-	if [ -f /var/run/emulab-watchdog.pid ]; then
-	    kill `cat /var/run/emulab-watchdog.pid` && echo -n ' Emulab'
-	fi
-	if [ -f /var/run/webserver.pid ]; then
-	    kill `cat /var/run/webserver.pid` && echo -n ' Webserver'
-	fi
-	;;
-*)
-	echo "Usage: `basename $0` {start|stop}" >&2
-	;;
-esac
+#
+# Must be root.
+# 
+if ($UID != 0) {
+    die("*** $0:\n".
+	"    Must be root to run this script!\n");
+}
 
-exit 0
+#
+# Turn off line buffering on output
+#
+$| = 1;
+
+# Drag in path stuff so we can find emulab stuff.
+BEGIN { require "/etc/emulab/paths.pm"; import emulabpaths; }
+
+#
+# Load the OS independent support library. It will load the OS dependent
+# library and initialize itself. 
+# 
+use libsetup;
+
+# Locals
+my $logname = "$LOGDIR/emulab-boot.debug";
+my $pidfile = "/var/run/emulab-boot.pid";
+my $noboot  = 0;
+my $debug   = 0;
+
+#
+# Parse command arguments. Once we return from getopts, all that should be
+# left are the required arguments.
+#
+%options = ();
+if (! getopts($optlist, \%options)) {
+    usage();
+}
+if (defined($options{"n"})) {
+    $noboot = 1;
+}
+if (defined($options{"d"})) {
+    $debug = 1;
+}
+if (@ARGV != 1) {
+    usage();
+}
+my $action = $ARGV[0];
+if ($action ne "start" && $action ne "stop") {
+    usage();
+}
+
+#
+# For stop, look to see if the pid file exists. If so, kill it and exit.
+#
+if ($action eq "stop") {
+    if (-e "/etc/emulab.pkey") {
+	system("webserver.pl stop");
+    }
+    system("watchdog stop");
+    if (! -e $pidfile) {
+	exit(0);
+    }
+    system("kill `cat $pidfile`");
+    exit($? >> 8);
+}
+
+#
+# Go to background. 
+# 
+#
+# Put this into the background and log its output. We *must* do this cause
+# we do not want to halt the boot if the testbed is down!
+# 
+if (!$debug && TBBackGround($logname)) {
+    #
+    # Parent exits normally
+    #
+    exit(0);
+}
+
+#
+# Write our pid into the pid file so we can be killed later (when the
+# experiment is torn down). We must do this first so that we can be
+# killed before we change the sig handlers.
+#
+system("echo '$PID' > $pidfile") == 0
+    or die("Could not create $pidfile!");
+
+#
+# Setup a handler to catch TERM, and kill our process group. Generally,
+# you do not want to send this a TERM, but use the stop argument instead.
+#
+my $pgrp = getpgrp(0);
+
+sub handler () {
+    $SIG{TERM} = 'IGNORE';
+    $SIG{INT} = 'IGNORE';
+    unlink($pidfile);
+    kill('TERM', -$pgrp);
+    sleep(1);
+    exit(0);
+}
+$SIG{TERM} = \&handler;
+$SIG{INT}  = \&handler;
+
+#
+# Run the tmcc commands in blocking mode. No point in continuing if we
+# cannot get a tmcd connection formed to tell it we are rebooting.
+# 
+print "Informing Emulab Operations that we've rebooted ...\n";
+system("tmcc state TBSETUP");
+
+#
+# Do a cvsup to get updated software.
+#
+print "Looking for software updates ... \n";
+system("runcvsup.sh");
+
+#
+# Do Apod.
+#
+print "Setting up APOD ... \n";
+system("rc.ipod");
+
+#
+# At bootup, look for new accounts.
+#
+print "Looking for new Emulab accounts ...\n";
+system("update -i");
+
+#
+# Do not start the mini server on RON nodes yet. 
+#
+if (-e "/etc/emulab.pkey") {
+    print "Starting up stub webserver ...\n";
+    system("webserver.pl start");
+}
+
+# Startup vnodes.
+if (! $noboot) {
+    print "Booting up vnodes ...\n";
+    system("bootvnodes -f");
+}
+
+# And the watchdog.
+print "Starting up the watchdog ...\n";
+system("watchdog");
+
+#
+# Inform TMCD that we are up and running.
+#
+print "Informing Emulab Operations that we're up and running ...\n";
+system("tmcc state ISUP");
+
+# Done!
+print "Done! Exiting ...\n";
+unlink($pidfile);
+exit(0);
+
