More robot integration and some event system updates.
	* configure, configure.in: Detect rsync for loghole and add
	utils/loghole to the list of template files.

	* db/libdb.pm.in, db/xmlconvert.in: Add virt_node_startloc to the
	list of virtual tables.

	* event/lib/event.h, event/lib/event.c, event/lib/tbevent.py.tail:
	Add event_stop_main function to break out of the event_main()
	loop.  Add timeline to the address tuple.

	* event/sched/GNUmakefile.in, event/sched/error-record.h,
	event/sched/error-record.c, event/sched/event-sched.8,
	event/sched/event-sched.h, event/sched/event-sched.c,
	event/sched/group-agent.h, event/sched/group-agent.c,
	event/sched/listNode.h, event/sched/listNode.c,
	event/sched/local-agent.h, event/sched/local-agent.c,
	event/sched/node-agent.h, event/sched/node-agent.cc,
	event/sched/queue.c, event/sched/rpc.h, event/sched/rpc.cc,
	event/sched/simulator-agent.h, event/sched/simulator-agent.c,
	event/sched/timeline-agent.h, event/sched/timeline-agent.c:
	Updated event scheduler, not completely finished, but well enough
	along for the robots.

	* lib/libtb/GNUmakefile.in, lib/libtb/popenf.h,
	lib/libtb/popenf.c, lib/libtb/systemf.h, lib/libtb/systemf.c: Add
	some handy versions of system/popen that take format arguments.

	* lib/libtb/tbdefs.h, lib/libtb/tbdefs.c: Add some more event and
	object types.

	* tbsetup/assign_wrapper.in: Add the virt_node_startloc building
	to desires string for a node.

	* tbsetup/ptopgen.in: Add a node's location to the feature list.

	* tbsetup/tbreport.in: Display the timeline/sequence an event is a
	part of.

	* tbsetup/ns2ir/GNUmakefile.in: Add timeline, sequence, and
	topography files.

	* tbsetup/ns2ir/node.tcl: Add initial position for nodes and allow
	them to be attached to "topographys".

	* tbsetup/ns2ir/parse-ns.in: Make a hwtype_class array with a
	node_type's class.  Make an 'areas' array that holds the
	buildings where nodes are located.  Make an 'obstacles' table
	with any obstacles in the building.

	* tbsetup/ns2ir/parse.tcl.in: Move named-args function from
	tb_compat.tcl to here.  Add reltime-to-secs function that converts
	time given in a format like "10h2m1s" to a seconds value, used in
	"$ns at" so its easier to write time values.  Add "K", "Kb", and
	"Kbps" as possible units for bandwidth (only the lowercase
	versions were available before).

	* tbsetup/ns2ir/program.tcl: Add "dir" and "timeout" attributes,
	although they don't go anywhere at the moment.

	* tbsetup/ns2ir/sequence.tcl, tbsetup/ns2ir/timeline.tcl,
	tbsetup/ns2ir/topography.tcl: Initial versions.

	* tbsetup/ns2ir/sim.tcl.in: Add support for timelines and
	sequences.  Add 'node-config' method to change the default
	configuration for nodes produced by the Simulator object.  Send an
	initial MODIFY event to any trafgen objects so their configuration
	gets through, even when there are no start/stop events.  Move
	event parsing to the 'make_event' method.

	* utils/loghole.1, utils/loghole.in: Loghole utility, used for
	retrieving logs from experimental nodes and creating archives of
	the logs.

	* xmlrpc/emulabclient.py.in: Escape any strange characters in the
	output field.

	* xmlrpc/emulabserver.py.in: Add virt_node_startloc to the list of
	virtual_tables.  Add emulab.vision_config and
	emulab.obstacle_config methods for getting information pertaining
	to the robots.  Change the OSID listing to include more fields.
	Add a "physical" aspect to experiment.info to get information
	about the physical nodes.  Add parent field to the events in the
	array returned by eventlist.  Add sshdescription to get extra
	information needed to log into a vnode.  Add node.statewait so you
	can wait for nodes to come up.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1839,6 +1839,45 @@ case "$INSTALL" in
         ;;
 esac
 
+# Extract the first word of "rsync", so it can be a program name with args.
+set dummy rsync; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:1811: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_RSYNC'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$RSYNC" in
+  /*)
+  ac_cv_path_RSYNC="$RSYNC" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_RSYNC="$RSYNC" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="${PATH}"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_RSYNC="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_RSYNC" && ac_cv_path_RSYNC=""""
+  ;;
+esac
+fi
+RSYNC="$ac_cv_path_RSYNC"
+if test -n "$RSYNC"; then
+  echo "$ac_t""$RSYNC" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+if test x"$RSYNC" = x"" || test ! -x "$RSYNC"; then
+    { echo "configure: error: Rsync is required to use this software, see www.rsync.org." 1>&2; exit 1; }
+fi
 
 outfiles="$outfiles Makeconf GNUmakefile \
 	assign/GNUmakefile \
@@ -1943,7 +1982,7 @@ outfiles="$outfiles Makeconf GNUmakefile \
 	utils/nsgen/GNUmakefile utils/nsgen/webnsgen \
 	utils/link_config utils/import_commitlog utils/dhcpd_wrapper \
 	utils/opsreboot utils/deletenode utils/webdeletenode utils/spewleds \
-	utils/grabwebcams \
+	utils/grabwebcams utils/loghole \
 	www/GNUmakefile www/defs.php3 www/dbdefs.php3 \
 	www/swish.conf www/websearch www/garcia-telemetry/GNUmakefile \
 	vis/GNUmakefile vis/webvistopology vis/dbvistopology \
@@ -2253,6 +2292,7 @@ s%@TESTMODE@%$TESTMODE%g
 s%@INSTALL_PROGRAM@%$INSTALL_PROGRAM%g
 s%@INSTALL_SCRIPT@%$INSTALL_SCRIPT%g
 s%@INSTALL_DATA@%$INSTALL_DATA%g
+s%@RSYNC@%$RSYNC%g
 s%@DISTCLEAN_FILES@%$DISTCLEAN_FILES%g
 
 CEOF
