A zillion configure/makefile changes, described in gory detail to the testbed list.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11,8 +11,11 @@
 ac_help=
 ac_default_prefix=/usr/local
 # Any additions from configure.in:
+ac_default_prefix=/usr/testbed
 ac_help="$ac_help
   --with-TBDBNAME=name		Specify TBDB name (tbdb default)"
+ac_help="$ac_help
+  --with-WWWDEFS=name		Specify WWW defintions ("default" default)"
 ac_help="$ac_help
   --with-LEDA			Specify LEDA path (/usr/testbed default)"
 ac_help="$ac_help
@@ -549,13 +552,14 @@ ac_configure=$ac_aux_dir/configure # This should be Cygnus configure.
 
 
 
+
 # Make sure we can run config.sub.
 if ${CONFIG_SHELL-/bin/sh} $ac_config_sub sun4 >/dev/null 2>&1; then :
 else { echo "configure: error: can not run $ac_config_sub" 1>&2; exit 1; }
 fi
 
 echo $ac_n "checking host system type""... $ac_c" 1>&6
-echo "configure:559: checking host system type" >&5
+echo "configure:563: checking host system type" >&5
 
 host_alias=$host
 case "$host_alias" in
@@ -576,7 +580,7 @@ host_os=`echo $host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 echo "$ac_t""$host" 1>&6
 
 echo $ac_n "checking build system type""... $ac_c" 1>&6
-echo "configure:580: checking build system type" >&5
+echo "configure:584: checking build system type" >&5
 
 build_alias=$build
 case "$build_alias" in
@@ -602,7 +606,7 @@ fi
 # Extract the first word of "${ac_tool_prefix}gcc", so it can be a program name with args.
 set dummy ${ac_tool_prefix}gcc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:606: checking for $ac_word" >&5
+echo "configure:610: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -634,7 +638,7 @@ fi
 # Extract the first word of "${ac_tool_prefix}g++", so it can be a program name with args.
 set dummy ${ac_tool_prefix}g++; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:638: checking for $ac_word" >&5
+echo "configure:642: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_CXX'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -666,7 +670,7 @@ fi
 # Extract the first word of "${ac_tool_prefix}ar", so it can be a program name with args.
 set dummy ${ac_tool_prefix}ar; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:670: checking for $ac_word" >&5
+echo "configure:674: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_AR'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -698,7 +702,7 @@ fi
 # Extract the first word of "${ac_tool_prefix}ranlib", so it can be a program name with args.
 set dummy ${ac_tool_prefix}ranlib; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:702: checking for $ac_word" >&5
+echo "configure:706: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_RANLIB'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -730,7 +734,7 @@ fi
 # Extract the first word of "${ac_tool_prefix}strip", so it can be a program name with args.
 set dummy ${ac_tool_prefix}strip; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:734: checking for $ac_word" >&5
+echo "configure:738: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_STRIP'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -761,11 +765,6 @@ fi
 
 
 #
-# overide with --prefix.
-# 
-ac_default_prefix=/usr/testbed
-
-#
 # Okay, I know this is improper usage of --with. Too bad.
 #
 # Check whether --with-TBDBNAME or --without-TBDBNAME was given.
@@ -780,6 +779,26 @@ if test "${with_TBDBNAME+set}" = set; then
 else
   
     TBDBNAME="tbdb"
+
+fi
+
+
+
+#
+# Okay, I know this is improper usage of --with. Too bad.
+#
+# Check whether --with-WWWDEFS or --without-WWWDEFS was given.
+if test "${with_WWWDEFS+set}" = set; then
+  withval="$with_WWWDEFS"
+  
+    if test "$withval" = "yes"; then
+	{ echo "configure: error: Invalid WWWDEFS - Must specify the value" 1>&2; exit 1; }
+    fi
+    WWWDEFS="$withval"
+
+else
+  
+    WWWDEFS="default"
 
 fi
 
@@ -840,7 +859,7 @@ fi
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
 echo $ac_n "checking for a BSD compatible install""... $ac_c" 1>&6
-echo "configure:844: checking for a BSD compatible install" >&5
+echo "configure:863: checking for a BSD compatible install" >&5
 if test -z "$INSTALL"; then
 if eval "test \"`echo '$''{'ac_cv_path_install'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -902,17 +921,31 @@ esac
 outfiles="$outfiles Makeconf GNUmakefile \
 	assign/GNUmakefile \
 	capture/GNUmakefile \
-	db/GNUmakefile \
+	db/GNUmakefile db/nalloc db/nfree \
 	discvr/GNUmakefile \
 	lib/GNUmakefile \
 	os/GNUmakefile os/imagezip/GNUmakefile \
 	pxe/GNUmakefile pxe/proxydhcp.restart pxe/bootinfo.restart \
-	security/GNUmakefile \
-	tbsetup/GNUmakefile tbsetup/ir/GNUmakefile tbsetup/ns2ir/GNUmakefile \
+	security/GNUmakefile security/paperbag \
+	tbsetup/GNUmakefile tbsetup/console_setup tbsetup/mkacct-ctrl \
+	tbsetup/os_load tbsetup/os_setup tbsetup/mkprojdir tbsetup/power \
+	tbsetup/resetvlans tbsetup/rmacct-ctrl tbsetup/rmprojdir \
+	tbsetup/sched_reload tbsetup/tbdoit tbsetup/tbstopit \
+	tbsetup/ir/GNUmakefile tbsetup/ir/postassign tbsetup/snmpit \
+	tbsetup/ir/assign_wrapper tbsetup/ns2ir/GNUmakefile \
+	tbsetup/ns2ir/postparse tbsetup/ir/handle_os tbsetup/ir/handle_ip \
+	tbsetup/ns2ir/parse.tcl \
 	tbsetup/checkpass/GNUmakefile \
 	tip/GNUmakefile \
 	tmcd/GNUmakefile tmcd/tmcd.restart \
-	www/GNUmakefile"
+	www/GNUmakefile www/defs.php3 www/dbdefs.php3"
+
+#
+# Do this for easy distclean.
+#
+DISTCLEAN_FILES="$outfiles"
+
+
 trap '' 1 2 15
 cat > confcache <<\EOF
 # This file is a shell script that caches the results of configure
@@ -1074,11 +1107,13 @@ s%@AR@%$AR%g
 s%@RANLIB@%$RANLIB%g
 s%@STRIP@%$STRIP%g
 s%@TBDBNAME@%$TBDBNAME%g
+s%@WWWDEFS@%$WWWDEFS%g
 s%@LEDA@%$LEDA%g
 s%@OPT_CFLAGS@%$OPT_CFLAGS%g
 s%@INSTALL_PROGRAM@%$INSTALL_PROGRAM%g
 s%@INSTALL_SCRIPT@%$INSTALL_SCRIPT%g
 s%@INSTALL_DATA@%$INSTALL_DATA%g
+s%@DISTCLEAN_FILES@%$DISTCLEAN_FILES%g
 
 CEOF
 EOF
@@ -1190,4 +1225,4 @@ EOF
 chmod +x $CONFIG_STATUS
 rm -fr confdefs* $ac_clean_files
 test "$no_create" = yes || ${CONFIG_SHELL-/bin/sh} $CONFIG_STATUS || exit 1
-	
+
