Cleanup rmcd a bit:
	* GNUmakerules: Quick fix to the "check" target.

	* robots/rmcd/rmcd.c, robots/rmcd/test_rmcd.sh.in: Cleanup the
	code a bit, add some comments, etc...

diff --git a/GNUmakerules b/GNUmakerules
--- a/GNUmakerules
+++ b/GNUmakerules
@@ -79,6 +79,9 @@ check: $(TESTS)
 		fi; \
 		if $$tst; then \
 			echo "PASS: $$tst"; \
+		else \
+			echo "FAIL: $$tst"; \
+			exit 1; \
 		fi \
 	done
 endif
