These files download tar.gz from www.emulab.net. I've added checks in case this fails to download that from the original location (www.postel.org for TG and www.isi.edu for NS)

diff --git a/event/nsetrafgen/nse-install b/event/nsetrafgen/nse-install
--- a/event/nsetrafgen/nse-install
+++ b/event/nsetrafgen/nse-install
@@ -1,7 +1,12 @@
 #!/bin/sh
 if [ ! -d ns-allinone-2.26 ]; then
-    echo "Downloading ns2.26 source ..."
+    echo "Downloading ns2.26 source from www.emulab.net"
     fetch http://www.emulab.net/ns-allinone-2.26.tar.gz
+    if [ $? -ne 0 ]; then
+        echo "Failed..."
+        echo "Downloading ns2.26 source from www.isi.edu"
+        fetch http://www.isi.edu/nsnam/dist/ns-allinone-2.26.tar.gz
+    fi
     tar xzf ns-allinone-2.26.tar.gz
     patch -p0 < nse.patch
 fi
diff --git a/event/trafgen/tg-install b/event/trafgen/tg-install
--- a/event/trafgen/tg-install
+++ b/event/trafgen/tg-install
@@ -1,10 +1,14 @@
 #!/bin/sh
 #	cd from <builddir>/event/trafgen to testbed/event/trafgen
 if [ ! -d $1/tg2.0/src ]; then
-    echo "Downloading tg2.0 source to $1 ..."
+    echo "Downloading tg2.0 source from www.emulab.net to $1 ..."
     cd $1
     fetch http://www.emulab.net/tg2.0.tar.gz
-    #fetch http://www.postel.org/tg/tg2.0.tar.gz
+    if [ $? -ne 0 ]; then
+         echo "Failed..."
+         echo "Downloading tg2.0 source from www.postel.org to $1 ..."
+         fetch http://www.postel.org/tg/tg2.0.tar.gz
+    fi
     echo "Unpacking/patching tg2.0 source ..."
     tar xzf tg2.0.tar.gz
     patch -p0 < tg.patch
