Frisbee MFS changes:  * support FreeBSD 6  * client-side changes to support enable/disable of ACPI via slicefix  * use dynamically linked Emulab binaries in frisbee MFS (for size)

diff --git a/tmcd/freebsd/slicefix b/tmcd/freebsd/slicefix
--- a/tmcd/freebsd/slicefix
+++ b/tmcd/freebsd/slicefix
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # EMULAB-COPYRIGHT
-# Copyright (c) 2000-2005 University of Utah and the Flux Group.
+# Copyright (c) 2000-2005, 2007 University of Utah and the Flux Group.
 # All rights reserved.
 #
 
@@ -25,6 +25,22 @@ case $# in
 *)
 	echo "Usage: $0 partition [disk]"
 	exit 1
+esac
+
+#
+# Handle pseudo arguments in the environment.
+#   
+ACPI=${SLICEFIX_ACPI:-'unknown'}
+case $ACPI in
+0|no|NO)
+    ACPI=no
+    ;;
+1|yes|YES)
+    ACPI=yes
+    ;;
+*)
+    ACPI=unknown
+    ;;
 esac
 
 dofreebsd() {
@@ -63,7 +79,7 @@ dofreebsd() {
 	#
 	# This is clearly not a solution.
 	#
-	version=`uname -v | sed -e 's/FreeBSD \([0-9]\).*/\1/'`
+	vers=`uname -v | sed -e 's/FreeBSD \([0-9]\).*/\1/'`
 
 	# see if there is a root ('a') partition on this BSD slice
 	`disklabel ${disk}s${part} 2>&1 | grep -s -E '^[ ]+a:' >/dev/null` || {
@@ -86,6 +102,7 @@ dofreebsd() {
 	#
 	changedisk=0
 	changeentropy=0
+	changeacpi=0
 
 	# If our disk does not appear anywhere in fstab, we need to fix it
 	grep "^/dev/${disk}s" /mnt/etc/fstab >/dev/null 2>&1
@@ -102,7 +119,40 @@ dofreebsd() {
 		changeentropy=1
 	fi
 
-	if [ $changedisk -eq 0 -a $changeentropy -eq 0 ]; then
+	#
+	# See if we need to change the ACPI setting.
+	#
+	# If ACPI was not specified via TMCD, leave it along.
+	#
+	# If "acpi_load" does not appear at all in the loader.conf file,
+	# assume the OS cannot handle it (or that we do not know how to
+	# change it) and leave it alone.
+	#
+	if [ $ACPI != "unknown" ]; then
+	    grep "acpi_load=" /mnt/boot/loader.conf >/dev/null 2>&1
+	    case $? in
+	    0)
+		grep "^acpi_load=\"YES\"" /mnt/boot/loader.conf >/dev/null 2>&1
+		case $? in
+		0)
+		    if [ $ACPI = "no" ]; then
+			changeacpi=1
+		    fi
+		    ;;
+		*)
+		    if [ $ACPI = "yes" ]; then
+			changeacpi=1
+		    fi
+		    ;;
+		esac
+		;;
+	    *)
+		;;
+	    esac
+	fi
+
+	if [ $changedisk -eq 0 -a $changeentropy -eq 0 -a $changeacpi -eq 0 ]; then
+		echo "  no changes necessary"
 		umount $rootdev
 		return 0
 	fi
@@ -134,11 +184,39 @@ dofreebsd() {
 	    dd if=/dev/random of=/mnt/entropy bs=4096 count=1 >/dev/null 2>&1
 	fi
 
+	if [ $changeacpi -eq 1 ]; then
+	    if [ $ACPI = "no" ]; then
+		on="dis"
+	    else
+		on="en"
+	    fi
+	    echo "  ${on}abling ACPI"
+	    sed -E -i .orig -e "/[Aa][Cc][Pp][Ii]/d" /mnt/boot/loader.conf || {
+		echo "Failed to update /boot/loader.conf"
+		umount $rootdev
+		return 1
+	    }
+	    if [ $ACPI = "no" ]; then
+		cat <<EOF1 >>/mnt/boot/loader.conf
+# disable ACPI
+acpi_load="NO"
+hint.acpi.0.disabled=1
+loader.acpi_disabled_by_user=1
+EOF1
+	    else
+		cat <<EOF2 >>/mnt/boot/loader.conf
+# enable ACPI
+acpi_load="YES"
+hint.acpi.0.disabled=0
+EOF2
+	    fi
+	fi
+
 	umount $rootdev
 
 	# XXX need to fixup FS, see big comment above
-	if [ "x$version" = "x5" ]; then
-		echo "WARNING: FBSD5 may have modified the UFS1 root FS"
+	if [ "x$vers" != "x4" ]; then
+		echo "WARNING: FBSD${vers} may have modified the UFS1 root FS"
 	fi
 
 	return 0
