A couple of fixes for the FreeBSD 8.x-based MFSes.
We apparently were not setting GID/EGID quite right in runstartup, it was
dropping a group. If that group happened to be "wheel", then any command
requiring "sudo" would fail. Now we set GID and EGID according to the letter
of the law.

If mount of a Linux FS fails, run e2fsck and try again. BSD cannot mount
a Linux FS if the ext3 journal requires recovery. e2fsck will handle that.

diff --git a/clientside/tmcc/freebsd/slicefix b/clientside/tmcc/freebsd/slicefix
--- a/clientside/tmcc/freebsd/slicefix
+++ b/clientside/tmcc/freebsd/slicefix
@@ -457,8 +457,13 @@ dolinux() {
 	rootdev=/dev/${disk}s${part}
 	echo "fixing Linux root partition ${disk}s${part}"
 	mount -t ext2fs $rootdev /mnt || {
-		echo "EXT2FS mount of $rootdev failed"
+	    # might need a journal recovery, try fsck
+	    echo "EXT2FS mount failed, trying recovery..."
+	    e2fsck -yf $rootdev
+	    mount -t ext2fs $rootdev /mnt || {
+		echo "EXT2FS mount failed"
 		return 1
+	    }
 	}
 
 	# hardwire the boss node
