Add node/node_type attribute "no_clflush".
This is for FreeBSD to turn off use of the CLFLUSH instruction via the
hw.clflush_disable loader var. We have encountered some opteron machines
on which this causes problems.

The attribute can be set for the node_type (via the web page for editing
node types) or the node (via brute-force SQL hackary) to override whatever
FreeBSD would do by default. This attribute is passed via tmcd to the
diskloader MFS which will fixup the loader.conf file post-frisbee.

diff --git a/clientside/tmcc/freebsd/slicefix b/clientside/tmcc/freebsd/slicefix
--- a/clientside/tmcc/freebsd/slicefix
+++ b/clientside/tmcc/freebsd/slicefix
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # EMULAB-COPYRIGHT
-# Copyright (c) 2000-2005, 2007 University of Utah and the Flux Group.
+# Copyright (c) 2000-2011 University of Utah and the Flux Group.
 # All rights reserved.
 #
 
@@ -30,7 +30,7 @@ esac
 
 #
 # Handle pseudo arguments in the environment.
-#   
+#
 ACPI=${SLICEFIX_ACPI:-'unknown'}
 case $ACPI in
 0|no|NO)
@@ -54,6 +54,19 @@ case $ASF in
     ;;
 *)
     ASF=unknown
+    ;;
+esac
+
+NOCLFLUSH=${SLICEFIX_NOCLFLUSH:-'unknown'}
+case $NOCLFLUSH in
+0|no|NO)
+    NOCLFLUSH=0
+    ;;
+1|yes|YES)
+    NOCLFLUSH=1
+    ;;
+*)
+    NOCLFLUSH=unknown
     ;;
 esac
 
@@ -134,6 +147,7 @@ dofreebsd() {
 	changeentropy=0
 	changeacpi=0
 	changeasf=0
+	changeclflush=0
 
 	fixit=0
 
@@ -226,6 +240,10 @@ dofreebsd() {
 	    esac
 	fi
 
+	if [ $NOCLFLUSH != "unknown" ]; then
+	    fixit=1
+	fi
+
         # check to see if we need to download any postconfig scripts:
 	doosconfig=0
 	if [ -x $BINDIR/osconfig ]; then
@@ -261,13 +279,13 @@ dofreebsd() {
 
 	if [ $changedisk -eq 1 ]; then
 	    echo "  updating /etc/fstab"
-	    sed -E -i .orig -e "s;^/dev/[a-zA-Z]+[0-9]+s[0-9]+;/dev/${disk}s${part};" /mnt/etc/fstab || {
+	    sed -E -i .preemulab -e "s;^/dev/[a-zA-Z]+[0-9]+s[0-9]+;/dev/${disk}s${part};" /mnt/etc/fstab || {
 		echo "Failed to update /etc/fstab"
 		umount $rootdev
 		return 1
 	    }
 	    echo "  updating /etc/dumpdates"
-	    sed -E -i .orig -e "s;^/dev/[a-zA-Z]+[0-9]+s[0-9]+;/dev/${disk}s${part};" /mnt/etc/dumpdates || {
+	    sed -E -i .preemulab -e "s;^/dev/[a-zA-Z]+[0-9]+s[0-9]+;/dev/${disk}s${part};" /mnt/etc/dumpdates || {
 		echo "Failed to update /etc/dumpdates"
 		umount $rootdev
 		return 1
@@ -279,6 +297,7 @@ dofreebsd() {
 	    dd if=/dev/random of=/mnt/entropy bs=4096 count=1 >/dev/null 2>&1
 	fi
 
+	lcbak=".preemulab"
 	if [ $changeacpi -eq 1 ]; then
 	    if [ $ACPI = "no" ]; then
 		on="dis"
@@ -286,11 +305,12 @@ dofreebsd() {
 		on="en"
 	    fi
 	    echo "  ${on}abling ACPI"
-	    sed -E -i .orig -e "/[Aa][Cc][Pp][Ii]/d" /mnt/boot/loader.conf || {
+	    sed -E -i $lcbak -e "/[Aa][Cc][Pp][Ii]/d" /mnt/boot/loader.conf || {
 		echo "Failed to update /boot/loader.conf"
 		umount $rootdev
 		return 1
 	    }
+	    lcbak=""
 	    if [ $ACPI = "no" ]; then
 		cat <<EOF1 >>/mnt/boot/loader.conf
 # disable ACPI
@@ -314,11 +334,12 @@ EOF2
 		on="en"
 	    fi
 	    echo "  ${on}abling ASF"
-	    sed -E -i .orig -e "/[Aa][Ss][Ff]/d" /mnt/boot/loader.conf || {
+	    sed -E -i $lcbak -e "/[Aa][Ss][Ff]/d" /mnt/boot/loader.conf || {
 		echo "Failed to update /boot/loader.conf"
 		umount $rootdev
 		return 1
 	    }
+	    lcbak=""
 	    if [ $ASF = "no" ]; then
 		cat <<EOF1 >>/mnt/boot/loader.conf
 # disable ASF
@@ -330,6 +351,29 @@ EOF1
 hw.bge.allow_asf=1
 EOF2
 	    fi
+	fi
+
+	#
+	# See if we need to change the use of NOCLFLUSH.
+	# If explicitly specified, we override any previous setting.
+	#
+	if [ $NOCLFLUSH != "unknown" ]; then
+	    if [ $NOCLFLUSH = "1" ]; then
+		on="dis"
+	    else
+		on="en"
+	    fi
+	    echo "  ${on}abling use of CLFLUSH"
+	    sed -E -i $lcbak -e "/clflush_disable/d" /mnt/boot/loader.conf || {
+		echo "Failed to update /boot/loader.conf"
+		umount $rootdev
+		return 1
+	    }
+	    lcbak=""
+	    cat <<EOF1 >>/mnt/boot/loader.conf
+# ${on}able CLFLUSH (hw.clflush_disable)
+hw.clflush_disable=$NOCLFLUSH
+EOF1
 	fi
 
 	# actually run any postconfig scripts if we're supposed to:
@@ -428,7 +472,7 @@ dolinux() {
 	fi
 
 	# change the swap devices in fstab
-	sed -i .orig -e "s;^/dev/[hs]d.\([0-7]\);/dev/${ldisk}\1;" /mnt/etc/fstab || {
+	sed -i .preemulab -e "s;^/dev/[hs]d.\([0-7]\);/dev/${ldisk}\1;" /mnt/etc/fstab || {
 		echo "Failed to update /etc/fstab"
 		umount $rootdev
 		return 1
@@ -446,7 +490,7 @@ dolinux() {
 	fi
 	if [ -r $gconf ]; then
 	    echo "  updating $fgconf"
-	    sed -i .orig -e "s;\([br]oot=/dev\)/[hs]d.[0-7];\1/${ldisk}${part};" $gconf || {
+	    sed -i .preemulab -e "s;\([br]oot=/dev\)/[hs]d.[0-7];\1/${ldisk}${part};" $gconf || {
 		echo "Failed to update $fgconf"
 	    }
 
@@ -477,7 +521,7 @@ dolinux() {
 	lconf=/mnt/etc/lilo.conf
 	if [ -r $lconf ]; then
 	    echo "  updating /etc/lilo.conf"
-	    sed -i .orig -e "s;\([br]oot=/dev\)/[hs]d.[0-7];\1/${ldisk}${part};" $lconf || {
+	    sed -i .preemulab -e "s;\([br]oot=/dev\)/[hs]d.[0-7];\1/${ldisk}${part};" $lconf || {
 		    echo "Failed to update /etc/lilo.conf"
 		    umount $rootdev
 		    return 1
diff --git a/clientside/tmcc/linux/slicefix b/clientside/tmcc/linux/slicefix
--- a/clientside/tmcc/linux/slicefix
+++ b/clientside/tmcc/linux/slicefix
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # EMULAB-COPYRIGHT
-# Copyright (c) 2000-2005, 2007 University of Utah and the Flux Group.
+# Copyright (c) 2000-2011 University of Utah and the Flux Group.
 # All rights reserved.
 #
 
@@ -65,6 +65,19 @@ case $ASF in
     ;;
 *)
     ASF=unknown
+    ;;
+esac
+
+NOCLFLUSH=${SLICEFIX_NOCLFLUSH:-'unknown'}
+case $NOCLFLUSH in
+0|no|NO)
+    NOCLFLUSH=0
+    ;;
+1|yes|YES)
+    NOCLFLUSH=1
+    ;;
+*)
+    NOCLFLUSH=unknown
     ;;
 esac
 
@@ -256,6 +269,10 @@ dofreebsd() {
 	    esac
 	fi
 
+	if [ $NOCLFLUSH != "unknown" ]; then
+	    fixit=1
+	fi
+
         # check to see if we need to download any postconfig scripts:
 	doosconfig=0
 	if [ -x $BINDIR/osconfig ]; then
@@ -299,7 +316,7 @@ dofreebsd() {
 	if [ $changedisk -eq 1 ]; then
 	    if [ -f /mnt/etc/fstab ]; then
 	    	    echo "  updating /etc/fstab"
-		    cp -fp /mnt/etc/fstab /mnt/etc/fstab.orig
+		    cp -fp /mnt/etc/fstab /mnt/etc/fstab.preemulab
 		    sed -i -e "s;^/dev/[a-zA-Z][a-zA-Z]*[0-9][0-9]*s[0-9][0-9]*;/dev/${freebsd_disk}s${part};" /mnt/etc/fstab || {
 			echo "Failed to update /etc/fstab"
 			umount $rootdev
@@ -308,7 +325,7 @@ dofreebsd() {
     	    fi
 	    if [ -f /mnt/etc/dumpdates ]; then
 		    echo "  updating /etc/dumpdates"
-		    cp -fp /mnt/etc/dumpdates /mnt/etc/dumpdates.orig
+		    cp -fp /mnt/etc/dumpdates /mnt/etc/dumpdates.preemulab
 		    sed -i -e "s;^/dev/[a-zA-Z][a-zA-Z]*[0-9][0-9]*s[0-9][0-9]*;/dev/${freebsd_disk}s${part};" /mnt/etc/dumpdates || {
 			echo "Failed to update /etc/dumpdates"
 			umount $rootdev
@@ -322,6 +339,7 @@ dofreebsd() {
 	    dd if=/dev/random of=/mnt/entropy bs=4096 count=1 >/dev/null 2>&1
 	fi
 
+	lcbak=".preemulab"
 	if [ $changeacpi -eq 1 ]; then
 	    if [ $ACPI = "no" ]; then
 		on="dis"
@@ -329,7 +347,10 @@ dofreebsd() {
 		on="en"
 	    fi
 	    echo "  ${on}abling ACPI"
-	    cp -fp /mnt/boot/loader.conf /mnt/boot/loader.conf.orig
+	    if [ -n "$lcbak" ]; then
+		cp -fp /mnt/boot/loader.conf /mnt/boot/loader.conf${lcbak}
+		lcbak=""
+	    fi
 	    sed -i -e "/[Aa][Cc][Pp][Ii]/d" /mnt/boot/loader.conf || {
 		echo "Failed to update /boot/loader.conf"
 		umount $rootdev
@@ -358,7 +379,10 @@ EOF2
 		on="en"
 	    fi
 	    echo "  ${on}abling ASF"
-	    cp -fp /mnt/boot/loader.conf /mnt/boot/loader.conf.orig
+	    if [ -n "$lcbak" ]; then
+		cp -fp /mnt/boot/loader.conf /mnt/boot/loader.conf${lcbak}
+		lcbak=""
+	    fi
 	    sed -i -e "/[Aa][Ss][Ff]/d" /mnt/boot/loader.conf || {
 		echo "Failed to update /boot/loader.conf"
 		umount $rootdev
@@ -375,6 +399,32 @@ EOF1
 hw.bge.allow_asf=1
 EOF2
 	    fi
+	fi
+
+	#
+	# See if we need to change the use of NOCLFLUSH.
+	# If explicitly specified, we override any previous setting.
+	#
+	if [ $NOCLFLUSH != "unknown" ]; then
+	    if [ $NOCLFLUSH = "1" ]; then
+		on="dis"
+	    else
+		on="en"
+	    fi
+	    echo "  ${on}abling use of CLFLUSH"
+	    if [ -n "$lcbak" ]; then
+		cp -fp /mnt/boot/loader.conf /mnt/boot/loader.conf${lcbak}
+		lcbak=""
+	    fi
+	    sed -E -i -e "/clflush_disable/d" /mnt/boot/loader.conf || {
+		echo "Failed to update /boot/loader.conf"
+		umount $rootdev
+		return 1
+	    }
+	    cat <<EOF1 >>/mnt/boot/loader.conf
+# ${on}able CLFLUSH (hw.clflush_disable)
+hw.clflush_disable=$NOCLFLUSH
+EOF1
 	fi
 
 	# actually run any postconfig scripts if we're supposed to:
