Make FBSD8 fsck happy.
For whatever reason, fsck on FreeBSD 8 cannot determine the FS type of the
root device. So if the straight fsck fails, we try again with "-t ufs".

diff --git a/clientside/tmcc/freebsd/slicefix b/clientside/tmcc/freebsd/slicefix
--- a/clientside/tmcc/freebsd/slicefix
+++ b/clientside/tmcc/freebsd/slicefix
@@ -132,8 +132,11 @@ dofreebsd() {
 	rootdev=/dev/${disk}s${part}a
 	echo "fixing FreeBSD root partition ${disk}s${part}a"
 	fsck -p $rootdev || {
-		echo "Fsck of $rootdev failed"
-		return 1
+		# 8.x fsck fails to determine the FS type, try again with ufs
+		fsck -t ufs -p $rootdev || {
+		    echo "Fsck of $rootdev failed"
+		    return 1
+		}
 	}
 	mount -o ro $rootdev /mnt || {
 		echo "RO-mount of $rootdev failed"
