Various nfstrace changes that have been sitting in my tree for awhile.
	* GNUmakefile.in: Do fs-install in the sensors subdir so the
	nfstracer gets installed.

	* sensors/and/and-emulab.priorities: Add some more daemon uid's to
	be excluded from auto-nicing.

	* sensors/and/and.c: Ignore invalid uids/gids in the config file
	instead of dying.

	* sensors/nfstrace/GNUmakefile: Makefile used to generate
	nfsdb-create.sql.

	* sensors/nfstrace/GNUmakefile.in: Some more installation stuff.

	* sensors/nfstrace/nfsdb-create.sql: SQL used to create the nfsdb
	database.

	* sensors/nfstrace/nfsdump2db: Bunch of bug fixes and cleanup.

	* sensors/nfstrace/nfsdump2db.8, sensors/nfstrace/nfstrace.7,
	sensors/nfstrace/nfstrace.proxy.8: Start at some man pages.

	* sensors/nfstrace/nfstrace.init.in: Try to detect the interface
	to listen on, not perfect though.  Add a restart handler that just
	restarts nfsdump2db.  Some other cleanup.

	* sensors/nfstrace/nfstrace.proxy: Some optimizations for
	resolving file names.

	* sensors/nfstrace/nfsdump2/*: Only print summaries of read/write
	packets and start a separate thread to read from the bpf socket.

	* tbsetup/tbswap.in: Stop transferring nfs accesses to boss' db
	until we figure out what we want to do with it.

diff --git a/sensors/nfstrace/GNUmakefile.in b/sensors/nfstrace/GNUmakefile.in
--- a/sensors/nfstrace/GNUmakefile.in
+++ b/sensors/nfstrace/GNUmakefile.in
@@ -11,6 +11,8 @@ TESTBED_SRCDIR  = @top_srcdir@
 OBJDIR          = ../..
 SUBDIR          = sensors/nfstrace
 
+NFSTRACESUPPORT = @NFSTRACESUPPORT@
+
 include $(OBJDIR)/Makeconf
 
 all: nfstrace.proxy nfsdump2db nfsdump nfstrace.init
@@ -27,6 +29,8 @@ INSTALL_SBIN=$(PREFIX)/sbin
 INSTALL_MAN=$(PREFIX)/man
 
 PW=/usr/sbin/pw
+NFSTRACE_HOME=/var/nfstrace
+NFSTRACE_DBDIR=/var/db/nfstrace
 
 $(SRCDIR)/nfsdump2/config.status:
 	cd $(SRCDIR)/nfsdump2 && ./configure
@@ -39,31 +43,100 @@ $(SRCDIR)/nfsdump2/nfsdump: $(SRCDIR)/nfsdump2/config.status make.nfsdump
 nfsdump: $(SRCDIR)/nfsdump2/nfsdump
 	cp $(SRCDIR)/nfsdump2/nfsdump .
 
-client client-install:
+client client-install control-install:
 
-control-install: all
-	-mkdir -p $(INSTALL_DIR)/sbin
-	-mkdir -p $(INSTALL_DIR)/etc
-	-mkdir -p $(INSTALL_DIR)/etc/rc.d
+$(NFSTRACE_HOME):
+	sudo mkdir -m 0750 $(NFSTRACE_HOME)
+
+add-nfstrace-user: $(NFSTRACE_HOME)
 	@if ! id nfstrace > /dev/null 2>&1; then \
-		sudo $(PW) useradd nfstrace -d /nonexistent \
+		sudo $(PW) useradd nfstrace -d $(NFSTRACE_HOME) \
 			-s /sbin/nologin -u 50,200 \
 			-c "NFS Tracing Daemon"; \
 	fi
-	@if ! $(PW) groupshow bpf; then \
-		sudo $(PW) groupadd bpf; \
+	@if ! id -Gn mysql | grep nfstrace > /dev/null 2>&1; then \
+		sudo $(PW) usermod -n mysql -G "`id -Gn mysql` nfstrace"; \
 	fi
-	@if test ! -d /var/nfstrace; then \
-		sudo mkdir -m 0750 /var/nfstrace; \
+	sudo chown nfstrace $(NFSTRACE_HOME)
+	sudo chgrp wheel $(NFSTRACE_HOME)
+	sudo chgrp nfstrace /dev/bpf0
+	sudo chmod g+r /dev/bpf0
+
+$(NFSTRACE_DBDIR):
+	sudo mkdir -m 0750 -p $@
+	sudo chown nfstrace $@
+	sudo chgrp nfstrace $@
+
+$(NFSTRACE_HOME)/dbpass:
+	head -c 32 /dev/urandom | md5 -q | head -c 8 > $@
+	sudo chown nfstrace $@
+	sudo chgrp wheel $@
+	sudo chmod o-r $@
+	@if test ! -s $@; then \
+		echo "error: generated empty password..."; \
+		rm $@; \
+		exit 1; \
 	fi
-	sudo chown nfstrace /var/nfstrace
+
+$(NFSTRACE_HOME)/.my.cnf: $(NFSTRACE_HOME)/dbpass
+	echo "[client]" > $@
+	echo "user=nfstrace" >> $@
+	echo "password=`cat $(NFSTRACE_HOME)/dbpass`" >> $@
+	echo "[mysqldump]" >> $@
+	echo "user=nfstrace" >> $@
+	echo "password=`cat $(NFSTRACE_HOME)/dbpass`" >> $@
+	sudo chown nfstrace $@
+	sudo chgrp wheel $@
+	sudo chmod o-r $@
+
+# XXX Needs to be updated to properly create the DB and user.
+create-db: $(NFSTRACE_HOME)/.my.cnf $(NFSTRACE_DBDIR)
+	@if ! id mysql > /dev/null 2>&1; then \
+		:; \
+	elif sudo -u nfstrace -H mysqldump -d nfsdb > nfsdb-dump.sql; then \
+		perl $(TESTBED_SRCDIR)/utils/schemadiff nfsdb-dump.sql \
+			$(SRCDIR)/nfsdb-create.sql > nfsdb.diff; \
+		if test -s nfsdb.diff; then \
+			echo "error: nfsdb is out of sync"; \
+			cat nfsdb.diff; \
+			exit 1; \
+		fi \
+	else \
+		echo "create database nfsdb" | sudo -u root mysql; \
+		sudo -u nfstrace -H mysql nfsdb < $(SRCDIR)/nfsdb-create.sql; \
+	fi
+
+ifeq ($(NFSTRACESUPPORT),1)
+fs-install: all add-nfstrace-user create-db
+	-mkdir -p $(INSTALL_DIR)/sbin
+	-mkdir -p $(INSTALL_DIR)/etc
+	-mkdir -p $(INSTALL_DIR)/etc/rc.d
 	$(INSTALL) -m 0755 nfsdump $(DESTDIR)$(INSTALL_SBINDIR)
 	$(INSTALL) -m 0755 $(SRCDIR)/nfsdump2db $(DESTDIR)$(INSTALL_SBINDIR)
 	$(INSTALL) -m 0755 $(SRCDIR)/nfstrace.proxy $(DESTDIR)$(INSTALL_SBINDIR)
 	$(INSTALL) -m 0755 nfstrace.init $(INSTALL_DIR)/etc/rc.d/nfstrace
+	-mkdir -p $(INSTALL_DIR)/man/man8
+	$(INSTALL) -m 0644 $(SRCDIR)/nfstrace.proxy.8 \
+		$(INSTALL_DIR)/man/man8/nfstrace.proxy.8
+	$(INSTALL) -m 0644 $(SRCDIR)/nfsdump2db.8 \
+		$(INSTALL_DIR)/man/man8/nfsdump2db.8
+	-mkdir -p $(INSTALL_DIR)/man/man7
+	$(INSTALL) -m 0644 $(SRCDIR)/nfstrace.7 \
+		$(INSTALL_DIR)/man/man7/nfstrace.7
 
 install: all
 	$(INSTALL) -m 0755 nfsdump $(DESTDIR)$(INSTALL_SBIN)
 	$(INSTALL) -m 0755 $(SRCDIR)/nfsdump2db $(DESTDIR)$(INSTALL_SBIN)
 	$(INSTALL) -m 0755 $(SRCDIR)/nfstrace.proxy $(DESTDIR)$(INSTALL_SBIN)
 	$(INSTALL) -m 0755 nfstrace.init $(DESTDIR)$(INSTALL_ETC)/rc.d/nfstrace
+	-mkdir -p $(INSTALL_DIR)/opsdir/man/man8
+	$(INSTALL) -m 0644 $(SRCDIR)/nfstrace.proxy.8 \
+		$(INSTALL_DIR)/opsdir/man/man8/nfstrace.proxy.8
+	$(INSTALL) -m 0644 $(SRCDIR)/nfsdump2db.8 \
+		$(INSTALL_DIR)/opsdir/man/man8/nfsdump2db.8
+	-mkdir -p $(INSTALL_DIR)/opsdir/man/man7
+	$(INSTALL) -m 0644 $(SRCDIR)/nfstrace.7 \
+		$(INSTALL_DIR)/opsdir/man/man7/nfstrace.7
+else
+fs-install install:
+endif
diff --git a/sensors/nfstrace/nfstrace.init.in b/sensors/nfstrace/nfstrace.init.in
--- a/sensors/nfstrace/nfstrace.init.in
+++ b/sensors/nfstrace/nfstrace.init.in
@@ -10,14 +10,26 @@ prefix=@prefix@
 exec_prefix=@exec_prefix@
 INSTALL_SBIN=@sbindir@
 
+# Execute as the nfstrace user.
 AS_NT="sudo -u nfstrace"
+# The nfstrace home directory.
 ND_DIR="/var/nfstrace"
+# Temporary file for nfsdump output.
 ND_TEMPNAME="${ND_DIR}/temp"
+# The base name for trace output.
 ND_BASENAME="${ND_DIR}/trace"
+# The number of trace files to use.
 ND_COUNT="10"
-ND_FLAGS="-s400 -I 1 -N $ND_COUNT -T $ND_TEMPNAME -B $ND_BASENAME"
-ND_FILTER="(port 2049 or port 900) and host fs and not host boss"
+# The interface to listen on for NFS traffic.  XXX Needs improvement.
+ND_IF=`/sbin/ifconfig -u -l | sed 's/lo0//' | cut -f 1 -d ' '`
+# Standard flags for nfsdump
+ND_FLAGS="-i $ND_IF -v -s400 -I 1 -N $ND_COUNT -T $ND_TEMPNAME -B $ND_BASENAME"
+ND_FLAGS="$ND_FLAGS -P"
+# BPF expression for nfsdump.  Captures NFS traffic between the FS node and the
+# experimental nodes.
+ND_FILTER="(port 2049 or port 900) and host @FSNODE@ and not @BOSSNODE@"
 
+# Build the list of trace file names.
 ND_TRACES=""
 
 lpc=0
@@ -33,6 +45,11 @@ case "$1" in
     start)
 	rm -f $ND_TRACES
 	echo -n "Starting nfstrace daemons:"
+	ps axuw | grep -v grep | grep ${INSTALL_SBIN}/nfsdump > /dev/null
+	if test $? -eq 0; then
+	    echo " already running"
+	    exit 0
+	fi
 	${AS_NT} \
 	    ${INSTALL_SBIN}/nfsdump $ND_FLAGS $ND_FILTER \
 	    > /var/nfstrace/nfsdump.log 2>&1 &
@@ -71,7 +88,32 @@ case "$1" in
 	exit 0
 	;;
     restart)
-	$0 stop  &&  $0 start
+	# Just restart the nfsdump2db daemon.  Need to do a full stop/start for
+	# nfsdump.
+	echo -n "Shutting down nfsdump2db daemon:"
+	ps axuw | grep -v grep | grep ${INSTALL_SBIN}/nfsdump2db > /dev/null
+	if test $? -eq 0; then
+	    ${AS_NT} kill `cat /var/nfstrace/nfsdump2db.pid`
+	    echo " done"
+	else
+	    echo " already stopped"
+	fi
+
+	rm -f $ND_TRACES
+	echo -n "Starting nfsdump2db daemon:"
+	${AS_NT} \
+	    ${INSTALL_SBIN}/nfsdump2db $ND_TRACES \
+	    > /var/nfstrace/nfsdump2db.log 2>&1 &
+	echo $! > /var/nfstrace/nfsdump2db.pid
+	ps axuw | grep -v grep | grep ${INSTALL_SBIN}/nfsdump2db \
+	    > /dev/null
+	if test $? -eq 0; then
+	    echo " done"
+	    exit 0
+	else
+	    echo " failed"
+	    exit 1
+	fi
 	exit 0
 	;;
     *)
